name: Auto approve and merge PRs by dependabot

# This workflow has been updated to fix several issues:
# 1. Updated to use latest dependabot/fetch-metadata@v2.2.0
# 2. Replaced deprecated pascalgn/automerge-action with GitHub CLI
# 3. Added explicit permissions for GITHUB_TOKEN
# 4. Improved trigger conditions
#
# REQUIREMENTS:
# - Auto-merge must be enabled on the repository (Settings > General > Pull Requests > "Allow auto-merge")
# - Branch protection rules should be configured to require status checks
# - The workflow will only run for dependabot PRs

# Trigger the workflow on pull request
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

# Add explicit permissions for GITHUB_TOKEN
permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    name: Auto Approve and merge PR by dependabot
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto approve
        uses: hmarr/auto-approve-action@v4.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge for dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
